package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 5, 2023, 5:31:43 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import th.ac.ku.kps.eng.cpe.soa.project.model.DTO.ReservationDTO;


/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	private int customerId;
	private String firstName;
	private String lastName;
	private String tel;
	@JsonIgnore
	private List<Payment> payments = new ArrayList<>();
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public Customer() {
	}

	public Customer(String firstName, String lastName, String tel) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.tel = tel;
	}

	public Customer(Integer customerId, String firstName, String lastName, String tel, List<Payment> payments,
			List<Reservation> reservations) {
		super();
		this.customerId = customerId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.tel = tel;
		this.payments = payments;
		this.reservations = reservations;
	}
	
	public void clone(Customer other) {
		this.firstName = other.firstName;
		this.lastName = other.lastName;
		this.tel = other.tel;
	}
	
	public void cloneDto(ReservationDTO dto) {
		this.firstName = dto.getFirstName();
		this.lastName = dto.getLastName();
		this.tel = dto.getTel();
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public List<Payment> getPayments() {
		return payments;
	}

	public void setPayments(List<Payment> payments) {
		this.payments = payments;
	}

	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

}
