package th.ac.ku.kps.eng.cpe.soa.project.model;

import com.fasterxml.jackson.annotation.JsonIgnore;

// Generated Apr 5, 2023, 6:40:37 PM by Hibernate Tools 5.6.3.Final

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer employeeId;
	@JsonIgnore
	private Role role;
	@JsonIgnore
	private Store store;
	private String name;
	private String email;
	private String phonenumber;

	public Employee() {
	}

	public Employee(Role role, Store store, String name, String email, String phonenumber) {
		this.role = role;
		this.store = store;
		this.name = name;
		this.email = email;
		this.phonenumber = phonenumber;
	}
	
	public void clone(Employee other) {
		this.name = other.name;
		this.email = other.email;
		this.phonenumber = other.phonenumber;
	}

	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

}
