package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 5, 2023, 5:31:43 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	@JsonIgnore
	private Customer customer;
	@JsonIgnore
	private Promotion promotion;
	@JsonIgnore
	private Reservation reservation;
	private String type;
	private double price;
	private Date currentDate;
	private String description;

	public Payment() {
	}

	public Payment(Customer customer, Promotion promotion, Reservation reservation, String type, double price,
			Date currentDate, String description) {
		this.customer = customer;
		this.promotion = promotion;
		this.reservation = reservation;
		this.type = type;
		this.price = price;
		this.currentDate = currentDate;
		this.description = description;
	}
	
	public void clone(Payment other) {
		this.type = other.type;
		this.price = other.price;
		this.currentDate = other.currentDate;
		this.description = other.description;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
