package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 6, 2023, 1:10:53 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	@JsonIgnore
	private Reservation reservation;
	private double price;
	private Date currentDate;

	public Payment() {
	}

	public Payment(Reservation reservation, double price, Date currentDate) {
		this.reservation = reservation;
		this.price = price;
		this.currentDate = currentDate;
	}
	
	public void clone(Payment other) {
		this.price = other.price;
		this.currentDate = other.currentDate;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

}
