package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 6, 2023, 1:10:53 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Price generated by hbm2java
 */
public class Price implements java.io.Serializable {

	private Integer priceId;
	private String name;
	private double amount;
	@JsonIgnore
	private List<Storeprice> storeprices = new ArrayList<Storeprice>();

	public Price() {
	}

	public Price(String name, double amount) {
		this.name = name;
		this.amount = amount;
	}

	public Price(Integer priceId, String name, double amount, List<Storeprice> storeprices) {
		super();
		this.priceId = priceId;
		this.name = name;
		this.amount = amount;
		this.storeprices = storeprices;
	}

	public Integer getPriceId() {
		return priceId;
	}

	public void setPriceId(Integer priceId) {
		this.priceId = priceId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public List<Storeprice> getStoreprices() {
		return storeprices;
	}

	public void setStoreprices(List<Storeprice> storeprices) {
		this.storeprices = storeprices;
	}

	
}
