package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 6, 2023, 1:10:53 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Promotion generated by hbm2java
 */
public class Promotion implements java.io.Serializable {

	private Integer promotionId;
	private String name;
	private double percentDiscount;
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public Promotion() {
	}

	public Promotion(String name, double percentDiscount) {
		this.name = name;
		this.percentDiscount = percentDiscount;
	}

	public Promotion(Integer promotionId, String name, double percentDiscount, List<Reservation> reservations) {
		super();
		this.promotionId = promotionId;
		this.name = name;
		this.percentDiscount = percentDiscount;
		this.reservations = reservations;
	}
	
	public void clone (Promotion other) {
		this.name = other.name;
		this.percentDiscount = other.percentDiscount;
	}

	public Integer getPromotionId() {
		return promotionId;
	}

	public void setPromotionId(Integer promotionId) {
		this.promotionId = promotionId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPercentDiscount() {
		return percentDiscount;
	}

	public void setPercentDiscount(double percentDiscount) {
		this.percentDiscount = percentDiscount;
	}

	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

	

}
