package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Province generated by hbm2java
 */
public class Province implements java.io.Serializable {

	private Integer provinceId;
	private String name;
	@JsonIgnore
	private List<District> districts = new ArrayList<District>();

	public Province() {
	}

	public Province(String name) {
		this.name = name;
	}

	public Province(Integer provinceId, String name, List<District> districts) {
		super();
		this.provinceId = provinceId;
		this.name = name;
		this.districts = districts;
	}

	public Integer getProvinceId() {
		return provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<District> getDistricts() {
		return districts;
	}

	public void setDistricts(List<District> districts) {
		this.districts = districts;
	}

}
