package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	@JsonIgnore
	private Promotion promotion;
	@JsonIgnore
	private Store store;
	@JsonIgnore
	private User user;
	private Date currentDate;
	private Date reservationDate;
	private String description;
	private Integer otherGroupId;
	@JsonIgnore
	private List<Payment> payments = new ArrayList<Payment>();

	public Reservation() {
	}

	public Reservation(Promotion promotion, Store store, User user, Date currentDate, Date reservationDate,
			String description) {
		this.promotion = promotion;
		this.store = store;
		this.user = user;
		this.currentDate = currentDate;
		this.reservationDate = reservationDate;
		this.description = description;
	}

	public Reservation(Integer reservationId, Promotion promotion, Store store, User user, Date currentDate,
			Date reservationDate, String description, Integer otherGroupId, List<Payment> payments) {
		super();
		this.reservationId = reservationId;
		this.promotion = promotion;
		this.store = store;
		this.user = user;
		this.currentDate = currentDate;
		this.reservationDate = reservationDate;
		this.description = description;
		this.otherGroupId = otherGroupId;
		this.payments = payments;
	}

	public Integer getReservationId() {
		return reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public Promotion getPromotion() {
		return promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Store getStore() {
		return store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getCurrentDate() {
		return currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	public Date getReservationDate() {
		return reservationDate;
	}

	public void setReservationDate(Date reservationDate) {
		this.reservationDate = reservationDate;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getOtherGroupId() {
		return otherGroupId;
	}

	public void setOtherGroupId(Integer otherGroupId) {
		this.otherGroupId = otherGroupId;
	}

	public List<Payment> getPayments() {
		return payments;
	}

	public void setPayments(List<Payment> payments) {
		this.payments = payments;
	}


}
