package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String name;
	private List<User> users = new ArrayList<User>();

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}

	public Role(Integer roleId, String name, List<User> users) {
		super();
		this.roleId = roleId;
		this.name = name;
		this.users = users;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<User> getUsers() {
		return users;
	}

	public void setUsers(List<User> users) {
		this.users = users;
	}

}
