package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 5, 2023, 5:31:43 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleId;
	private String name;
	@JsonIgnore
	private List<Employee> employees = new ArrayList<>();

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}

	public Role(Integer roleId, String name, List<Employee> employees) {
		super();
		this.roleId = roleId;
		this.name = name;
		this.employees = employees;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(List<Employee> employees) {
		this.employees = employees;
	}

	

}
