package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 6, 2023, 1:10:53 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Storeprice generated by hbm2java
 */
public class Storeprice implements java.io.Serializable {

	private Integer storepriceId;
	private Price price;
	@JsonIgnore
	private Store store;
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public Storeprice() {
	}

	public Storeprice(Price price, Store store) {
		this.price = price;
		this.store = store;
	}

	public Storeprice(Integer storepriceId, Price price, Store store, List<Reservation> reservations) {
		super();
		this.storepriceId = storepriceId;
		this.price = price;
		this.store = store;
		this.reservations = reservations;
	}
	
	public void clone(Storeprice other) {
		this.price = price;
	}

	public Integer getStorepriceId() {
		return storepriceId;
	}

	public void setStorepriceId(Integer storepriceId) {
		this.storepriceId = storepriceId;
	}

	public Price getPrice() {
		return price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	public Store getStore() {
		return store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

	

}
