package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 5, 2023, 5:31:43 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Subdistrict generated by hbm2java
 */
public class Subdistrict implements java.io.Serializable {

	private Integer subdistrictId;
	@JsonIgnore
	private District district;
	private String name;
	@JsonIgnore
	private List<Store> stores = new ArrayList<>();

	public Subdistrict() {
	}

	public Subdistrict(District district, String name) {
		this.district = district;
		this.name = name;
	}

	public Subdistrict(Integer subdistrictId, District district, String name, List<Store> stores) {
		super();
		this.subdistrictId = subdistrictId;
		this.district = district;
		this.name = name;
		this.stores = stores;
	}

	public Integer getSubdistrictId() {
		return subdistrictId;
	}

	public void setSubdistrictId(Integer subdistrictId) {
		this.subdistrictId = subdistrictId;
	}

	public District getDistrict() {
		return district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Store> getStores() {
		return stores;
	}

	public void setStores(List<Store> stores) {
		this.stores = stores;
	}

	

}
