package th.ac.ku.kps.eng.cpe.soa.project.model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.ArrayList;
import java.util.List;


import com.fasterxml.jackson.annotation.JsonIgnore;



/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	@JsonIgnore
	private Role role;
	private String name;
	private String email;
	private String phonenumber;
	@JsonIgnore
	private List<Store> stores = new ArrayList<Store>();
	@JsonIgnore
	private List<Payment> payments = new ArrayList<Payment>();
	@JsonIgnore
	private List<Reservation> reservations = new ArrayList<Reservation>();

	public User() {
	}

	public User(Role role, String name, String email, String phonenumber) {
		this.role = role;
		this.name = name;
		this.email = email;
		this.phonenumber = phonenumber;
	}

	public User(Integer userId, Role role, String name, String email, String phonenumber,
			List<Store> stores, List<Payment> payments, List<Reservation> reservations) {
		super();
		this.userId = userId;
		this.role = role;
		this.name = name;
		this.email = email;
		this.phonenumber = phonenumber;
		this.stores = stores;
		this.payments = payments;
		this.reservations = reservations;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhonenumber() {
		return phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	public List<Store> getStores() {
		return stores;
	}

	public void setStores(List<Store> stores) {
		this.stores = stores;
	}

	public List<Payment> getPayments() {
		return payments;
	}

	public void setPayments(List<Payment> payments) {
		this.payments = payments;
	}

	public List<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(List<Reservation> reservations) {
		this.reservations = reservations;
	}

}
