package model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Payment generated by hbm2java
 */
public class Payment implements java.io.Serializable {

	private Integer paymentId;
	private Promotion promotion;
	private Reservation reservation;
	private User user;
	private String type;
	private double price;
	private Date currentDate;
	private String description;

	public Payment() {
	}

	public Payment(Promotion promotion, Reservation reservation, User user, String type, double price, Date currentDate,
			String description) {
		this.promotion = promotion;
		this.reservation = reservation;
		this.user = user;
		this.type = type;
		this.price = price;
		this.currentDate = currentDate;
		this.description = description;
	}

	public Integer getPaymentId() {
		return this.paymentId;
	}

	public void setPaymentId(Integer paymentId) {
		this.paymentId = paymentId;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Reservation getReservation() {
		return this.reservation;
	}

	public void setReservation(Reservation reservation) {
		this.reservation = reservation;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
