package model;
// Generated Apr 5, 2023, 6:40:37 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer reservationId;
	private Customer customer;
	private Promotion promotion;
	private Store store;
	private Date currentDate;
	private Date reservationDate;
	private String description;
	private Integer otherGroupId;
	private Set payments = new HashSet(0);

	public Reservation() {
	}

	public Reservation(Customer customer, Promotion promotion, Store store, Date currentDate, Date reservationDate,
			String description) {
		this.customer = customer;
		this.promotion = promotion;
		this.store = store;
		this.currentDate = currentDate;
		this.reservationDate = reservationDate;
		this.description = description;
	}

	public Reservation(Customer customer, Promotion promotion, Store store, Date currentDate, Date reservationDate,
			String description, Integer otherGroupId, Set payments) {
		this.customer = customer;
		this.promotion = promotion;
		this.store = store;
		this.currentDate = currentDate;
		this.reservationDate = reservationDate;
		this.description = description;
		this.otherGroupId = otherGroupId;
		this.payments = payments;
	}

	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Promotion getPromotion() {
		return this.promotion;
	}

	public void setPromotion(Promotion promotion) {
		this.promotion = promotion;
	}

	public Store getStore() {
		return this.store;
	}

	public void setStore(Store store) {
		this.store = store;
	}

	public Date getCurrentDate() {
		return this.currentDate;
	}

	public void setCurrentDate(Date currentDate) {
		this.currentDate = currentDate;
	}

	public Date getReservationDate() {
		return this.reservationDate;
	}

	public void setReservationDate(Date reservationDate) {
		this.reservationDate = reservationDate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getOtherGroupId() {
		return this.otherGroupId;
	}

	public void setOtherGroupId(Integer otherGroupId) {
		this.otherGroupId = otherGroupId;
	}

	public Set getPayments() {
		return this.payments;
	}

	public void setPayments(Set payments) {
		this.payments = payments;
	}

}
