package model;
// Generated Apr 1, 2023, 2:32:11 PM by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Store generated by hbm2java
 */
public class Store implements java.io.Serializable {

	private Integer storeId;
	private Subdistrict subdistrict;
	private User user;
	private String name;
	private Date openTime;
	private Date closeTime;
	private String phoneNumber;
	private String type;
	private Set reservations = new HashSet(0);

	public Store() {
	}

	public Store(Subdistrict subdistrict, String name, Date openTime, Date closeTime, String phoneNumber, String type) {
		this.subdistrict = subdistrict;
		this.name = name;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.phoneNumber = phoneNumber;
		this.type = type;
	}

	public Store(Subdistrict subdistrict, User user, String name, Date openTime, Date closeTime, String phoneNumber,
			String type, Set reservations) {
		this.subdistrict = subdistrict;
		this.user = user;
		this.name = name;
		this.openTime = openTime;
		this.closeTime = closeTime;
		this.phoneNumber = phoneNumber;
		this.type = type;
		this.reservations = reservations;
	}

	public Integer getStoreId() {
		return this.storeId;
	}

	public void setStoreId(Integer storeId) {
		this.storeId = storeId;
	}

	public Subdistrict getSubdistrict() {
		return this.subdistrict;
	}

	public void setSubdistrict(Subdistrict subdistrict) {
		this.subdistrict = subdistrict;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	public Date getCloseTime() {
		return this.closeTime;
	}

	public void setCloseTime(Date closeTime) {
		this.closeTime = closeTime;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
