package model;
// Generated Apr 5, 2023, 6:40:37 PM by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subdistrict generated by hbm2java
 */
public class Subdistrict implements java.io.Serializable {

	private Integer subdistrictId;
	private District district;
	private String name;
	private Set stores = new HashSet(0);

	public Subdistrict() {
	}

	public Subdistrict(District district, String name) {
		this.district = district;
		this.name = name;
	}

	public Subdistrict(District district, String name, Set stores) {
		this.district = district;
		this.name = name;
		this.stores = stores;
	}

	public Integer getSubdistrictId() {
		return this.subdistrictId;
	}

	public void setSubdistrictId(Integer subdistrictId) {
		this.subdistrictId = subdistrictId;
	}

	public District getDistrict() {
		return this.district;
	}

	public void setDistrict(District district) {
		this.district = district;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getStores() {
		return this.stores;
	}

	public void setStores(Set stores) {
		this.stores = stores;
	}

}
